# Generated by Django 6.0.6 on 2026-06-16 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_cel_user_cel_wspolne_przychod_user_przychod_wspolne_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wplata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('opis', models.CharField(blank=True, max_length=200)),
                ('cel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wplaty', to='tracker.cel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
