# Generated by Django 6.0.6 on 2026-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wydatek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('kwota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategoria', models.CharField(choices=[('jedzenie', 'Jedzenie'), ('transport', 'Transport'), ('rozrywka', 'Rozrywka'), ('zdrowie', 'Zdrowie'), ('inne', 'Inne')], max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
